### ISSUE TITLE
Allow configuring protected branches in Quarkiverse repositories

### ISSUE THREAD

**Issue by yrodiere** [quarkiverse/quarkiverse#106]
I'd like to use GitHub's auto-merge feature in https://github.com/quarkiverse/quarkus-hibernate-search-extras/, and I can check that box, which is great!

But... auto-merge implies that PRs must pass certain automated checks before they are merged automatically. And the definition of required checks is done through the configuration of protected branches. And at the moment, I don't seem to have access to that for my repository (probably missing access rights?).

Could we get access to configuration of protected branches on Quarkiverse repositories?

**Comment by yrodiere** [comment]
Hey @gastaldi , any opinion on this?

**Comment by gastaldi** [comment]
@yrodiere hey, this is achieved by providing a PR changing the Terraform file in https://github.com/quarkiverse/quarkiverse-devops/blob/main/quarkus-hibernate-search-extras.tf. 

See https://registry.terraform.io/providers/integrations/github/latest/docs/resources/branch_protection on what to change.

Be aware that the release process may fail depending on what you enable (eg. Require Signed commits is known to fail)

Let me know if you need help with that

**Comment by yrodiere** [comment]
Ah, it's configured that way... I had more in mind to tell Terraform "this part, users will manage manually through the web UI". Like we allow enabling the auto-merge feature on the web UI, for example.

Thank you @gastaldi , I will have a closer look at the code config then.
