### ISSUE TITLE
 migrate 3.x script error

### ISSUE THREAD

**Issue by naah69** [quarkiverse/quarkiverse#111]
i read this document to migrate extension to 3.x,but i found some problems.
https://github.com/quarkiverse/quarkiverse/wiki/Migrating-to-Quarkus-3.x#upgrade

i use the below command to migrate,but it error.
```bash
curl -Ls https://sh.jbang.dev | bash -s - --fresh upgrade-to-quarkus3@quarkusio
```

error log:
```log
(base) ➜  quarkus-dapr git:(main) ✗ curl -Ls https://sh.jbang.dev | bash -s - --fresh upgrade-to-quarkus3@quarkusio
[jbang] [ERROR] Unknown catalog 'quarkusio'
[jbang] Run with --verbose for more details

```

**Comment by gastaldi** [comment]
Please report in the Quarkus issue tracker if this is still an issue. I ran the command above and it executed fine in my laptop
