### ISSUE TITLE
Apache Shiro Security Extension

### ISSUE THREAD

**Issue by Alffrredo** [quarkiverse/quarkiverse#12]
Hello folks,

That`s a great feature to add apache shiro repo for those who wants to use apache shiro as authentication and authorization mechanism in their apps and services

**Comment by gastaldi** [comment]
@Alffrredo thanks! Can you create this issue as an [Extension Proposal](https://github.com/quarkusio/quarkus/issues/new?assignees=&labels=kind%2Fextension-proposal&template=extension_proposal.md&title=) in the Quarkus repository? 

I'll close it for now

Thank you!
