### ISSUE TITLE
Add contribute section in footer 

### ISSUE THREAD

**Issue by shivarm** [quarkiverse/quarkiverse#154]
Add contribute section in footer with github icon 

![image](https://github.com/quarkiverse/quarkiverse/assets/91419219/0e7aeb2c-7aed-49da-9ecd-914aacd76bf6)

**Comment by shivarm** [comment]
@gastaldi @holly-cummins WDYT?

**Comment by holly-cummins** [comment]
Would the Contribute section in the footer be a bit redundant with the 'Edit this page' section in the header?

**Comment by gastaldi** [comment]
I agree with @holly-cummins, the `Edit this page` section exists for this purpose

**Comment by shivarm** [comment]
@holly-cummins @gastaldi I agree but it't look cool because most of the time people check `footer` for further thing.

**Comment by holly-cummins** [comment]
I suppose it would improve the symmetry of the footer, and send an inclusive message.

**Comment by shivarm** [comment]
> I suppose it would improve the symmetry of the footer, and send an inclusive message.

@holly-cummins Should I open a PR for this?

**Comment by holly-cummins** [comment]
> @holly-cummins Should I open a PR for this?

Ok!
