### ISSUE TITLE
How quarkiverse extensions can deal with RedHat build of Quarkus versions?

### ISSUE THREAD

**Issue by vietk** [quarkiverse/quarkiverse#36]
Hello,

I am one of the contributor the [quarkus-splunk-extension](https://github.com/quarkiverse/quarkus-logging-splunk) and I have some questions about the branch policy regarding multiple version of Quarkus.

Inside my company we follow the ["Redhat build of Quarkus"](https://access.redhat.com/products/quarkus) versions, we call that an "LTS" (Long Term Support) version even if not appropriate. Beside that we came to contribute to the Splunk extension because we rely on Splunk also.

In the extension, we need today, to bump Quarkus community version on our main branch but this version is not the one we are internally using. It means that an extension (might) have to support :  
* the open-source community, in order to have the latest version of Quarkus on the main branch
* the private companies (us) that uses LTS version of Quarkus: we want to have the possibility to patch the extension (i.e bump the main thirdparty of the extension) but keep on with the same version of Quarkus.

I ask the question today here, because we can find a convention for each and every extension that would follow the "RedHat build of Quarkus" versions.

**My proposal is the following :**
* The main branch of the extension is reserved to the community version of Quarkus. Dependabot bumps Quarkus without restrictions and other dependencies with or without restrictions depending the need of the extension. 
* A dedicated branch is created for "RedHat build of Quarkus" versions. Dependabot bumps only the patched version of Quarkus and other dependencies with or without restrictions depending the need of the extension. The extension is maintained on this branch and fix or feature are backported to the main branch.

**Then what about the versioning ?**
The versioning is the tricky part because we would have to maintain a compatibility matrix. Also if the extension choose to follow [semver](https://semver.org/), which [Quarkus seems not following](https://groups.google.com/g/quarkus-dev/c/iRAWMES7bIk/m/OdsbSRXYBwAJ), we may need to bump the major version of the extension for each minor release of Quarkus.
However, only one RedHat build of Quarkus is supported at same time, meaning that an extension could have to maintain only a limited set of branch at the same time, i.e:
* The main branch
* The current RedHat build of Quarkus branch

Then, a possible matrix would be the following : 

the-quarkus-extension version | Quarkus version | git branch
-- | -- | --
1.x.y | 1.11.z | quarkus-1_11/
2.x.y | 1.13.z | main/
_In the near future ..._
3.x.y | 2.0.z | quarkus-2_0/
4.x.y | 2.1.z | main/
_In the future of the future ..._
7.x.y | 2.10.z | quarkus-2_10/
8.x.y | 2.13.z | main/

Now, I await quarkiverse users/maintainers feedback or decision about this proposal. The solution is not perfect so any counter proposal is welcome.
In case there's no comments on feedback, we will probably use this proposal in the extension we contribute to. If the proposal change, we'll post a message on what we did. 

Best regards

**Comment by rquinio1A** [comment]
Just some remarks:

> A dedicated branch is created for "RedHat build of Quarkus" versions. Dependabot bumps only the patched version of Quarkus and other dependencies with or without restrictions depending the need of the extension. 

Based on what's happening on [quarkus-universe-bom](https://github.com/quarkusio/quarkus-platform), I think extensions only need to be released for each new Quarkus minor version, so I assume Quarkus patch versions are binary compatible on extension APIs (BuildItems, etc.), so we may not even need to bump Quarkus - unless for a bugfix needed for the extension own tests.

> The extension is maintained on this branch and fix or feature are backported to the main branch.

Quarkus repo does the reverse: fix on main and then backport, which is probably more natural since `main` is the default target branch of pull requests. But for bugfix on dependencies, dependabot could maybe open PRs on both branches, so we only need manual backport of manual PRs.

**Comment by gastaldi** [comment]
Just a friendly reminder that extensions depending on the LTS may not be deployed to Maven Central, because they live in a separate repository

**Comment by vietk** [comment]
Good point. 
I think there's a low risk of breaking things between LTS and community version of an extension since they will depend on the "same" core.

**Comment by aloubyansky** [comment]
Quarkus release versions do not accurately express backward compatibility contracts. I wouldn't rely on that in your update policies.
We are actually working on the mechanism and tools that would allow you to update both the Quarkus platform version(s) and the Quarkiverse extensions used in your application.
If the RHBQ and the community Quarkus diverge significantly enough for your extension to create and maintain separate branches then, yes, you would need to create a branch for the Quarkus community version that was the base for the RHBQ you are using (the corresponding branch will actually exist in the Quarkus repo). You wouldn't need to actually depend on the RHBQ in your community branch.
Then once you release your extension depending on the community version of Quarkus (that is the base for the RHBQ you are using), our tools will collect information about that release and will be suggesting that version of your extension for the RHBQ.

**Comment by maxandersen** [comment]
My assumption is you could have a branch named after quarkus major version it's based on. 

Shouldn't need to explicit depend on rhbq. 

If that would be needed we broke something we shouldn't have and should fix that.

**Comment by vietk** [comment]
Thanks all for your inputs.

The fact is there's already a "divergence" between 1.11 and 1.13 that [broke our extension](https://github.com/quarkiverse/quarkus-logging-splunk/pull/12).

So as everybody suggests it : we'll create a branch after the name of the Quarkus major, corresponding to the current supported RHBQ but pointing to the corresponding community version, then we hope binary compatibility not to be broken between RHBQ and the community version. 
In the case the binary compatibility is broken, we  could still create another branch to point to publicly available of RHBQ, it will have impacts in term of maven repository in project POMS, but nothing really blocking.

Last thing: since we can't spare having a compatibility matrix we could use it to avoid creating a branch after the RHBQ if nothing is broken in our extension, users (at least us 😄 ) will follow it.

**Comment by maxandersen** [comment]
I can't see what the change was that broke you but if that is a unexpected breakage please do open issues against quarkus core. 

Btw. Was this not found in ecosystem-ci or is this extension not yet participating ?

**Comment by gastaldi** [comment]
Indeed it was not participating. I opened https://github.com/quarkusio/quarkus-ecosystem-ci/pull/50 to include it
