### ISSUE TITLE
Quarkus XML Security

### ISSUE THREAD

**Issue by martinffx** [quarkiverse/quarkiverse#47]
I would like to make a XML Security extension.

I've run into the following issue when native compiling my quarkus service that relies on Apache XML Security:

https://stackoverflow.com/questions/69393827/apache-xml-security-with-quarkus-native

Camel Quarkus have an extension that registers all the classes to native compile Apache XML Security but it relies on pulling the whole of Apache Camel as a dependency.

https://github.com/apache/camel-quarkus/blob/main/extensions/xmlsecurity

I would like to add an extension that just adds support to native compile projects that rely on XML Security.

**Comment by gastaldi** [comment]
@martinffx I created https://github.com/quarkiverse/quarkus-xmlsec and gave you Maintainer permission to push

**Comment by martinffx** [comment]
Thank you!
