### ISSUE TITLE
Improve indexing of wiki, perhaps by moving it entirely to docs?

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkiverse#93]
As discussed in https://github.com/quarkusio/quarkusio.github.io/pull/1593, the wiki currently isn't indexed by google. This makes it much less useful as a store of information. The content we put in the wiki is basically invisible, unless we share a direct link to it for someone, or someone is very enterprising in manually navigating from a known starting point.

It seems like the origin of the limitation on indexing wikis is to prevent comment-spam and other publically-generatable content being indexed. We don't have publically-generatable content, but the limitation still applies. https://github.com/github/docs/issues/4115 suggests using GitHub pages as a workaround.

Since we do have other places to publish information, such as the normal docs, I wonder if we should reconsider where some/all of this content lives. 

Opening this work item to track the discussion of the pros and cons.

**Comment by holly-cummins** [comment]
cc @gastaldi @maxandersen

**Comment by gastaldi** [comment]
I agree. This information should be on the main page of the Quarkiverse docs (https://quarkiverse.github.io/quarkiverse-docs/ as of now)

**Comment by holly-cummins** [comment]
See also discussion: https://groups.google.com/g/quarkus-dev/c/MijWx9HyaWo

**Comment by holly-cummins** [comment]
> I agree. This information should be on the main page of the Quarkiverse docs (https://quarkiverse.github.io/quarkiverse-docs/ as of now)

I wondered about this, but I think even though the site name would be almost the same, the audience is different; that site is for hosting user-facing information, and a lot of the wiki content is contributor-facing.

**Comment by gastaldi** [comment]
IMHO that doesn't necessarily mean that they should live in separate places. Centralizing everything in the Quarkiverse docs is preferable. 

We could even enable comments as we do with blog posts (eg. https://quarkus.io/blog/quarkus-newsletter-33/), something that is not possible in GitHub Wikis

**Comment by holly-cummins** [comment]
I think we can close this, now that https://hub.quarkiverse.io is live. I've confirmed that it is indexed, so searches will take you to the site, although so far the SEO of the site isn't great so searches have to be fairly specific.
